name: BoxStaff
version: '1.0-SNAPSHOT'
main: us.boxpvp.boxstaff.BoxStaff
authors: [ lSantih ]
api-version: 1.16
depend:
  - SUtils
description: Private plugin developed for McVox
commands:
  freeze:
    description: Froze a player.
  setfreezelocation:
    description: Set the location of the freeze area.
  staffmode:
    description: Toggles your staff mode.
    aliases: staff,h,mod
  vanish:
    description: Toggles your vanish status.
  inspect:
    description: Inspect a player inventory..
  rollback:
    description: Manages rollback..